"""add projection tables

Revision ID: 0da793676103
Revises: 4786fa28ed93
Create Date: 2026-04-05 22:32:57.957446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0da793676103'
down_revision: Union[str, None] = '4786fa28ed93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_price_isin_fetched_at', 'prices', ['isin', 'fetched_at'])
    op.add_column('securities', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_column('securities', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('securities', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_column('securities', 'created_at')
    op.drop_constraint('uq_price_isin_fetched_at', 'prices', type_='unique')
    # ### end Alembic commands ###
