"""add day_change_pct to prices

Revision ID: 3e24da44b626
Revises: 0da793676103
Create Date: 2026-04-06 10:59:32.236848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e24da44b626'
down_revision: Union[str, None] = '0da793676103'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('performance_metrics_portfolio_id_key'), 'performance_metrics', type_='unique')
    op.drop_index(op.f('ix_performance_metrics_portfolio_id'), table_name='performance_metrics')
    op.create_index(op.f('ix_performance_metrics_portfolio_id'), 'performance_metrics', ['portfolio_id'], unique=True)
    op.add_column('prices', sa.Column('day_change_pct', sa.Numeric(precision=10, scale=4), nullable=True))
    op.drop_constraint(op.f('securities_isin_key'), 'securities', type_='unique')
    op.drop_index(op.f('ix_securities_isin'), table_name='securities')
    op.create_index(op.f('ix_securities_isin'), 'securities', ['isin'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_securities_isin'), table_name='securities')
    op.create_index(op.f('ix_securities_isin'), 'securities', ['isin'], unique=False)
    op.create_unique_constraint(op.f('securities_isin_key'), 'securities', ['isin'], postgresql_nulls_not_distinct=False)
    op.drop_column('prices', 'day_change_pct')
    op.drop_index(op.f('ix_performance_metrics_portfolio_id'), table_name='performance_metrics')
    op.create_index(op.f('ix_performance_metrics_portfolio_id'), 'performance_metrics', ['portfolio_id'], unique=False)
    op.create_unique_constraint(op.f('performance_metrics_portfolio_id_key'), 'performance_metrics', ['portfolio_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
