"""add indexes and unique constraint

Revision ID: 45e1a89153bf
Revises: d4d4e9c2d605
Create Date: 2026-04-05 13:24:39.724559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45e1a89153bf'
down_revision: Union[str, None] = 'd4d4e9c2d605'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_entity_access', 'family_user_access', ['user_id', 'entity_id'])
    op.create_index(op.f('ix_portfolio_events_portfolio_id'), 'portfolio_events', ['portfolio_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_portfolio_events_portfolio_id'), table_name='portfolio_events')
    op.drop_constraint('uq_user_entity_access', 'family_user_access', type_='unique')
    # ### end Alembic commands ###
