"""add_documents_staged_extractions

Revision ID: 4786fa28ed93
Revises: 45e1a89153bf
Create Date: 2026-04-05 17:15:34.173167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4786fa28ed93'
down_revision: Union[str, None] = '45e1a89153bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('portfolio_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.Enum('email', 'upload', name='documentsource'), nullable=False),
    sa.Column('doc_type', sa.Enum('contract_note', 'pms_transaction', 'cas', 'bank_statement', name='doctype'), nullable=True),
    sa.Column('storage_path', sa.Text(), nullable=True),
    sa.Column('preprocessed_text', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('pending', 'classifying', 'preprocessing', 'extracting', 'normalizing', 'awaiting_review', 'ingested', 'failed', 'rejected_sender', name='documentstatus'), nullable=False),
    sa.Column('failure_reason', sa.String(length=500), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_entity_id'), 'documents', ['entity_id'], unique=False)
    op.create_table('staged_extractions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('extracted_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('review_status', sa.Enum('pending', 'approved', 'rejected', name='reviewstatus'), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('staged_extractions')
    op.drop_index(op.f('ix_documents_entity_id'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
